#!/usr/bin/env python
"""Generate Outcomes dashboard MOC (pending decision reviews)."""
from __future__ import annotations

import datetime
import sys
from pathlib import Path

VAULT = Path(__file__).resolve().parent.parent
if str(VAULT) not in sys.path:
    sys.path.insert(0, str(VAULT))

from knowledgeos.evolution import decisions_with_lessons, pending_outcome_reviews  # noqa: E402
from knowledgeos.memory import MemoryAPI  # noqa: E402

OUT = VAULT / "MOCs" / "_MOC_Outcomes.md"


def main() -> int:
    api = MemoryAPI(VAULT)
    today = datetime.date.today()
    try:
        pending = pending_outcome_reviews(api)
        lessons = decisions_with_lessons(api)
    except FileNotFoundError as e:
        print(e, file=sys.stderr)
        return 1

    lines = [
        "---",
        "type: moc",
        "title: Outcomes Dashboard",
        "description: Generated view of pending decision outcomes and lessons ready for Self promotion.",
        "schema: knowledgeos-v0.3",
        "status: active",
        f"created: {today}",
        f"updated: {today}",
        f"timestamp: {today.isoformat()}T00:00:00Z",
        "tags: [moc, outcomes, decisions, generated]",
        "project: KnowledgeOS",
        "---",
        "# Outcomes Dashboard",
        "",
        "Auto-generated by `python scripts/outcomes_dashboard.py` (via `update_mocs.py`).",
        "",
        "## Pending outcome reviews",
        "",
    ]
    if pending:
        for r in pending:
            flag = "**OVERDUE**" if r.get("overdue") else "awaiting"
            lines.append(
                f"- [{r['title']}](../{r['path']}) — {flag}; "
                f"review_after={r.get('review_after') or '—'}; "
                f"status={r.get('outcome_status') or 'pending'}"
            )
    else:
        lines.append("- None.")

    lines += ["", "## Closed decisions with lessons (promote to Self?)", ""]
    if lessons:
        for r in lessons:
            lesson = (r.get("lesson") or "")[:160]
            lines.append(
                f"- [{r['title']}](../{r['path']}) — `{r.get('outcome_status')}` — {lesson}"
            )
        lines += [
            "",
            "```bash",
            "python scripts/propose_self_update.py from-lesson Decisions/your-decision.md",
            "```",
        ]
    else:
        lines.append("- None yet.")

    lines += [
        "",
        "## Loop reminder",
        "",
        "Capture → Clarify → Connect → Decide → Execute → **Record Outcome** → Review → **Update Self**",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
