#!/usr/bin/env python
"""Setup Git Hooks for KnowledgeOS.

Creates a local pre-commit hook that runs schema validation.
Works with Git for Windows (sh hooks) and Unix.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

VAULT_DIR = Path(__file__).resolve().parent.parent
HOOKS_DIR = VAULT_DIR / ".git" / "hooks"


def main() -> int:
    if not HOOKS_DIR.parent.exists():
        print("Error: Not a Git repository (missing .git/ directory).")
        return 1

    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    hook_file = HOOKS_DIR / "pre-commit"

    # Use the current interpreter so Windows/venv python resolves correctly.
    python_exe = Path(sys.executable).as_posix()
    validate_script = (VAULT_DIR / "scripts" / "validate_schema.py").as_posix()
    vault_posix = VAULT_DIR.as_posix()

    hook_content = f"""#!/bin/sh
# KnowledgeOS pre-commit schema validation (generated by setup_git_hooks.py)
echo "Running KnowledgeOS pre-commit schema validation..."
cd "{vault_posix}" || exit 1
"{python_exe}" "{validate_script}"
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "Git commit aborted: KnowledgeOS schema validation failed."
  exit $EXIT_CODE
fi
"""

    print(f"[*] Writing pre-commit hook to {hook_file}...")
    hook_file.write_text(hook_content, encoding="utf-8", newline="\n")

    if os.name == "posix":
        try:
            status = hook_file.stat()
            os.chmod(hook_file, status.st_mode | 0o111)
            print("[OK] Execution permission set.")
        except Exception as e:
            print(f"[WARNING] Could not set execution permission: {e}")
    else:
        # Git for Windows executes #!/bin/sh hooks via its bundled sh.
        print("[OK] Wrote sh hook (Git for Windows compatible).")

    print("[OK] Git pre-commit hook setup successfully!")
    return 0


if __name__ == "__main__":
    sys.exit(main())
